---
openapi: 3.0.1
info:
  title: Video Cropping Api V1
  version: v1
paths:
  "/api/v1/users":
    post:
      summary: Creates a User
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
              required: []
  "/api/v1/videos":
    post:
      summary: Uploads videos by authorized user
      tags:
      - Videos
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '401':
          description: unauthorized
          content: {}
        '201':
          description: created
          content: {}
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                input_video:
                  type: file
                  example: "#<Rack::Test::UploadedFile:0x00005559eecd3f78>"
                start_time_trim:
                  type: integer
                  example: 10
                end_time_trim:
                  type: integer
                  example: 50
              required:
              - start_time_trim
              - end_time_trim
              - input_video
    get:
      summary: Get list all video by specific user
      tags:
      - User Videos
      parameters:
      - name: Authorization
        in: header
        default: Token 8b6a04aac0264bef89d99c3cc5fd8513
        schema:
          type: string
      - name: page
        in: query
        description: 'Page number. Default: 1'
        required: false
        schema:
          type: integer
      - name: per_page
        in: query
        description: 'Per page items. Default: 30'
        required: false
        schema:
          type: integer
      responses:
        '200':
          description: success
          content: {}
  "/api/v1/videos/{id}/reload":
    post:
      summary: Reload video by id
      tags:
      - Reload Video
      parameters:
      - name: Authorization
        in: header
        default: Token 8b6a04aac0264bef89d99c3cc5fd8513
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  collection:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        input_video:
                          type: object
                          properties:
                            url:
                              type: string
                            duration:
                              type: integer
                        output_video:
                          type: object
                          properties:
                            url:
                              type: string
                            duration:
                              type: integer
                        processing_errors:
                          type: string
                        start_time_trim:
                          type: integer
                        end_time_trim:
                          type: integer
                        input_video_duration:
                          type: integer
                        output_video_duration:
                          type: integer
                        status:
                          type: string
                        created_at:
                          type: string
                        updated_at:
                          type: string
        '404':
          description: not_found
          content: {}
servers:
- url: http://localhost:3000/
  variables:
    defaultHost:
      default: localhost:3000
