---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users":
    post:
      summary: Creates a User
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
              required: []
  "/api/v1/videos":
    post:
      summary: Uploads videos by authorized user
      tags:
      - Videos
      parameters:
      - name: Authorization
        in: header
        default: Token 8b6a04aac0264bef89d99c3cc5fd8513
        schema:
          type: string
      - name: video
        in: fromData
        schema:
          type: object
          properties:
            start_time_trim:
              type: integer
              example: 10
            end_time_trim:
              type: integer
              example: 50
          required:
          - start_time_trim
          - end_time_trim
      responses:
        '401':
          description: unauthorized
          content: {}
        '201':
          description: created
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: file
servers:
- url: http://localhost:3000/
  variables:
    defaultHost:
      default: localhost:3000
